version: '3.3'

services:
    app:
        build:
            context: .
            dockerfile: ./docker/app/Dockerfile
        volumes:
            - '.:/app:cached'
            - './docker/app/nginx/nginx.conf:/etc/nginx/nginx.conf'
            - './docker/app/nginx/sites-enabled:/etc/nginx/sites-enabled'
            - './docker/app/nginx/sites-available:/etc/nginx/sites-available'
        working_dir: /app
        env_file:
            - .env
            - .env.local
        ports:
            - '80:80'
            - '443:443'

volumes:
    volume:
