framework:
    cache:
        pools:
            messenger_mapper.cache:
                adapter: messenger_mapper.cache.adapter.php_files

messenger_cache:
    pools:
        messenger_mapper.cache: messenger_mapper.cache

services:
    messenger_mapper.cache.adapter.php_files:
        class: Symfony\Component\Cache\Adapter\PhpFilesAdapter
        arguments:
            - messenger_mapper.cache
            - 0
            - '%kernel.cache_dir%/MessengerMapper/'
            - true
