services:
    _defaults:
        autowire: true
        autoconfigure: true

    PBaszak\DedicatedMapper\:
        resource: '../../*'
        exclude:
            - '../../{Resources,DependencyInjection,DedicatedMapper.php,Mapper.php}'

    PBaszak\DedicatedMapper\Contract\MapperServiceInterface:
        alias: PBaszak\DedicatedMapper\MapperService
        public: true
    
    PBaszak\DedicatedMapper\MapperService:
        arguments:
            $directory: '%kernel.project_dir%/var/mapper/'

    PBaszak\DedicatedMapper\ValidatedMapperService:
        public: true
        arguments:
            $directory: '%kernel.project_dir%/var/mapper/'
