services:
    _defaults:
        autowire: true
        autoconfigure: true

    PBaszak\DedicatedMapper\:
        resource: '../../*'
        exclude:
            - '../../{Resources,DependencyInjection,DedicatedMapperBundle.php,Mapper.php}'

    pbaszak.dedicated_mapper.encoder:
        public: true
        alias: PBaszak\DedicatedMapper\Encoder

    pbaszak.dedicated_mapper:
        public: true
        alias: PBaszak\DedicatedMapper\Mapper

    pbaszak.dedicated_mapper.mapper:
        public: true
        alias: pbaszak.dedicated_mapper

    pbaszak.dedicated_mapper.normalizer:
        public: true
        alias: PBaszak\DedicatedMapper\Normalizer

    pbaszak.dedicated_mapper.serializer:
        public: true
        alias: PBaszak\DedicatedMapper\Serializer
    
    PBaszak\DedicatedMapper\Contract\EncoderInterface:
        alias: pbaszak.dedicated_mapper.encoder
        public: true

    PBaszak\DedicatedMapper\Contract\MapperInterface:
        alias: pbaszak.dedicated_mapper
        public: true

    PBaszak\DedicatedMapper\Contract\NormalizerInterface:
        alias: pbaszak.dedicated_mapper.normalizer
        public: true

    PBaszak\DedicatedMapper\Contract\SerializerInterface:
        alias: pbaszak.dedicated_mapper.serializer
        public: true

    PBaszak\DedicatedMapper\Mapper:
        public: true
        arguments:
            $directory: '%kernel.project_dir%/var/mapper/'
