services:
    _defaults:
        autowire: true
        autoconfigure: true

    PBaszak\MessengerMapperBundle\:
        resource: '../../*'
        exclude:
            - '../../{Resources,DependencyInjection,MessengerMapperBundle.php,Mapper.php}'

    PBaszak\MessengerMapperBundle\Contract\MapperServiceInterface:
        alias: PBaszak\MessengerMapperBundle\MapperService
        public: true
    
    PBaszak\MessengerMapperBundle\MapperService:
        arguments:
            $directory: '%kernel.project_dir%/var/mapper/'
