services:
    _defaults:
        autowire: true
        autoconfigure: true

    PBaszak\DedicatedMapperBundle\:
        resource: '../../*'
        exclude:
            - '../../{Resources,DependencyInjection,DedicatedMapperBundle.php,Mapper.php}'

    PBaszak\DedicatedMapperBundle\Contract\MapperServiceInterface:
        alias: PBaszak\DedicatedMapperBundle\MapperService
        public: true
    
    PBaszak\DedicatedMapperBundle\MapperService:
        arguments:
            $directory: '%kernel.project_dir%/var/mapper/'

    PBaszak\DedicatedMapperBundle\ValidatedMapperService:
        public: true
        arguments:
            $directory: '%kernel.project_dir%/var/mapper/'
