services:
    _defaults:
        autowire: true
        autoconfigure: true

    PBaszak\MessengerMapperBundle\:
        resource: '../../*'
        exclude:
            - '../../{Resources,DependencyInjection,MessengerMapperBundle.php,Mapper.php}'

    PBaszak\MessengerMapperBundle\Mapper:
        public: true

    PBaszak\MessengerMapperBundle\Handler\GetMapperHandler:
        tags: 
            - { name: 'messenger.message_handler', handles: PBaszak\MessengerMapperBundle\GetMapper }
